# Generated by Django 4.1.7 on 2023-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="slackoauthstate",
            index=models.Index(
                fields=["state"], name="core_slacko_state_dbac4e_idx"
            ),
        ),
    ]
