# Generated by Django 4.1.9 on 2023-05-16 10:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_slackoauthstate_core_slacko_state_dbac4e_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo", models.TextField(null=True)),
                ("owner", models.TextField(null=True)),
                (
                    "channels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=21),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot_token",
                    models.ForeignKey(
                        db_column="bot_token",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="core.slackinstallation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["bot_token", "repo", "owner"],
                name="core_notifi_bot_tok_4e39c8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("bot_token", "repo", "owner")},
        ),
    ]
