# Generated by Django 4.1.9 on 2023-05-15 10:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_slackoauthstate_core_slacko_state_dbac4e_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_token", models.TextField(null=True)),
                ("repo", models.TextField(null=True)),
                ("owner", models.TextField(null=True)),
                (
                    "channels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=21),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["bot_token", "repo", "owner"],
                name="core_notifi_bot_tok_4e39c8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("bot_token", "repo", "owner")},
        ),
    ]
