# Generated by Django 4.1.9 on 2023-05-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_notification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackinstallation",
            name="bot_token",
            field=models.TextField(null=True, unique=True),
        ),
    ]
