# Generated by Django 4.2.1 on 2023-06-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_notificationstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationstatus",
            old_name="message_ts",
            new_name="message_timestamp",
        ),
    ]
