# Generated by Django 4.2.3 on 2023-08-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_message_ts_notificationstatus_message_timestamp"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="slackinstallation",
            name="core_slacki_client__d43855_idx",
        ),
        migrations.AddIndex(
            model_name="slackinstallation",
            index=models.Index(
                fields=[
                    "client_id",
                    "enterprise_id",
                    "team_id",
                    "user_id",
                    "installed_at",
                    "bot_token",
                ],
                name="core_slacki_client__f623ea_idx",
            ),
        ),
    ]
