# Generated by Django 4.2.3 on 2023-08-14 15:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_message_ts_notificationstatus_message_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo", models.TextField(null=True)),
                ("owner", models.TextField(null=True)),
                ("channel", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "filters",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_config",
                        to="core.slackinstallation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationConfigStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        default="success",
                        max_length=7,
                    ),
                ),
                ("pullid", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_timestamp", models.TextField(null=True)),
                (
                    "notification_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_config_statuses",
                        to="core.notificationconfig",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["notification_config", "status", "pullid"],
                        name="core_notifi_notific_b85a75_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notificationconfig",
            index=models.Index(
                fields=["installation", "repo", "owner", "channel"],
                name="core_notifi_install_8ea80a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationconfig",
            unique_together={("installation", "repo", "owner", "channel")},
        ),
    ]
