# Generated by Django 4.1.7 on 2023-04-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_userid",
            field=models.CharField(max_length=50),
        ),
    ]
