# Generated by Django 4.2.1 on 2023-06-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0003_alter_slackinstallation_bot_token_notification_and_more",
        ),
        ("service_auth", "0003_alter_service_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slackuser",
            name="team_id",
        ),
        migrations.AddField(
            model_name="slackuser",
            name="installation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slackuser",
                to="core.slackinstallation",
            ),
        ),
    ]
