# Generated by Django 4.2.1 on 2023-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_auth", "0003_alter_service_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackuser",
            name="codecov_access_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
