# Generated by Django 4.2.1 on 2023-06-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_auth", "0004_remove_slackuser_team_id_slackuser_installation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackuser",
            name="codecov_access_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
