from enum import Enum


class EndpointName(Enum):
    SERVICE_OWNERS = "organizations"
    OWNER = "owner"
    USERS_LIST = "users"
    REPO_CONFIG = "repo-config"
    REPOS = "repos"
    REPO = "repo"
    BRANCHES = "branches"
    BRANCH = "branch"
    COMMITS = "commits"
    COMMIT = "commit"
    PULLS = "pulls"
    PULL = "pull"
    COMPONENTS = "components"
    FLAGS = "flags"
    COVERAGE_TRENDS = "coverage-trends"
    COMPARISON = "compare"
    COMPONENT_COMPARISON = "compare-component"
    FILE_COMPARISON = "compare-file"
    FLAG_COMPARISON = "compare-flag"
    COVERAGE_TREND = "coverage-trend"
    FILE_COVERAGE_REPORT = "file-coverage-report"
    COMMIT_COVERAGE_REPORT = "commit-coverage-report"
    COMMIT_COVERAGE_TOTALS = "commit-coverage-totals"
